### ISSUE TITLE
Documentation issues regarding "rendererStateKeyValueChanged" and "Volume"

### ISSUE THREAD

**Issue by Alex9779** [ChriD/node-raumkernel#33]
So working with setting and getting volumes I based my work on the example in the README.
But as far as I can tell this does not work:
```
raumkernel.on("rendererStateKeyValueChanged", function(_mediaRenderer, _key, _oldValue, _newValue, _roomUdn){
		if(key=="Volume")
			console.log("Volume on " + _mediaRenderer.name() + " changed to " + _newValue.toString());
	})
```
The parameter is "_key" but the function then uses "key".

The next example has the same problem.

Also the event does never pass "_roomUdn". I dug into the code and it is missing everywhere except at the very bottom. Here you set the room UDN on the virtual renderer: https://github.com/ChriD/node-raumkernel/blob/5f5c3599d75e7e5b02ed7f675c3634163f2119b6/lib/lib.device.upnp.mediaRenderer.raumfeldVirtual.js#L122
But the definitions above like at https://github.com/ChriD/node-raumkernel/blob/5f5c3599d75e7e5b02ed7f675c3634163f2119b6/lib/lib.manager.deviceManager.js#L451 and https://github.com/ChriD/node-raumkernel/blob/5f5c3599d75e7e5b02ed7f675c3634163f2119b6/lib/lib.raumkernel.js#L267 do not contain the parameter. In conclusion it is not passed to my event.

Finally I found that what the documentation says is not correct: "The _mediaRenderer is the virtual renderer in case if _roomUdn is filled"
Virtual media renderers do not give "Volume" as the key but "volume". Just normal raumfeld renderes emit the key with a capital "V".

I didn't create a PR for this because I am not absolutely sure how to fix this properly keeping the project's goals and design as I have no complete understanding of the whole project, just of some parts for now...

**Comment by ChriD** [comment]
Thank you @Alex9779  for your input!

You are right. The roomUdn should be provided by the `lib.device.upnp.mediaRenderer.raumfeldVirtual.js` and it should be emitted throughout the whole System. I have fixed this issue this in version 1.2.10

Further i have changed some key of the rooms section to  be equal to the keys of standard renderer keys (lowercase/upercase), I fixed it for Volume, Mute and TransportState

And i have corrected the documentation samples

**Comment by Alex9779** [comment]
:thumbsup:  :smiley:

**Comment by Alex9779** [comment]
Sorry to say but I think you forgot this line here:
https://github.com/ChriD/node-raumkernel/blob/8c62a375105f28d34440f27ef26e86d7ebcd9567/lib/lib.raumkernel.js#L99

**Comment by ChriD** [comment]
Damn it...
Fixed it!
Thanks!
